### ISSUE TITLE
Failed to activate the Scratchpad package

### ISSUE THREAD

**Issue by twizzlynn** [brianzable/Scratchpad#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Scratchpad](https://github.com/brianzable/Scratchpad) package, v0.7.0

### Stack Trace

Failed to activate the Scratchpad package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/flynn/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:1:1)
  at /Users/flynn/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:5:3
  at Object.<anonymous> (/Users/flynn/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:75:5)
  at Object.<anonymous> (/Users/flynn/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/flynn/.atom/packages/Scratchpad/lib/scratchpad.coffee:1:18)
  at Object.<anonymous> (/Users/flynn/.atom/packages/Scratchpad/lib/scratchpad.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:707:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:255:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:234:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -3:41.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:37 editor:newline (atom-text-editor.editor.is-focused)
  3x -3:35.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:34.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:02.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:59.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -1:22.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:20.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  8x -1:19.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:15.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:31.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:19.7.0 core:cut (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 scratchpad:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "git-grep"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Scratchpad, v0.7.0
color-picker, v2.0.4
language-jade, v0.4.0
linter, v0.12.6
linter-eslint, v0.5.8
linter-flake8, v1.4.2
minimap, v4.9.4
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by cheshirecatalyst** [comment]
+1

**Comment by eddflrs** [comment]
Bumped into this one today.

**Comment by mrthebob** [comment]
+1

**Comment by mdlincoln** [comment]
+1

**Comment by jtryan** [comment]
Still an issue :+1:

**Comment by townie** [comment]
+1

**Comment by shemerey** [comment]
@brianzable I've done some fix, check this out
