### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by bastiaanterhorst** [brianzable/Scratchpad#6]
[Enter steps to reproduce below:]

1. install the package

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Scratchpad](https://github.com/brianzable/Scratchpad) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/bastiaan/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/bastiaan/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:4:199)
  at /Users/bastiaan/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:5:3
  at Object.<anonymous> (/Users/bastiaan/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:75:5)
  at Object.<anonymous> (/Users/bastiaan/.atom/packages/Scratchpad/lib/scratchpad-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/bastiaan/.atom/packages/Scratchpad/lib/scratchpad.coffee:1:18)
  at Object.<anonymous> (/Users/bastiaan/.atom/packages/Scratchpad/lib/scratchpad.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -7:45.3.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:43.4.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -7:41.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -7:40.6.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -7:38.2.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:37.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -7:36.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:35.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -7:34.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:33.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -7:33.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -7:32.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:32.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:03.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:57.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:51.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autocomplete-ruby, v0.1.0
language-SCSS, v0.4.0
language-slim, v0.4.0
meteor-api, v2.19.0

# Dev
No dev packages
```

**Comment by shemerey** [comment]
save for me
